name: snackstore
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  provider: ^6.0.3
  flutter_dotenv: ^5.0.2
  http: ^0.13.4
  shared_preferences: ^2.0.15
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
  fonts:
    - family: Lato
      fonts:
      - asset: assets/fonts/Lato-Bold.ttf
      - asset: assets/fonts/Lato-Regular.ttf
        weight: 700
    - family: Anton
      fonts: 
        - asset: assets/fonts/Anton-Regular.ttf
    - family: ArianaVioleta
      fonts:
        - asset: assets/fonts/ArianaVioleta-dz2K.ttf
    - family: ShortBaby
      fonts:
        - asset: assets/fonts/ShortBaby-Mg2w.ttf
    - family: OpenSans
      fonts: 
        - asset: assets/fonts/OpenSans-Italic-VariableFont_wdth,wght.ttf
        - asset: assets/fonts/OpenSans-VariableFont_wdth,wght.ttf